### ISSUE TITLE
Lacks project description and license

### ISSUE THREAD

**Issue by jmiskovic** [warmist/lua-halfedge#1]
This project piqued my interest because it has pure Lua implementations of mesh modifiers like bevel, extrude, spike. I would like to use such library within 3D engine that operates in standard OpenGL vertices format.

@warmist can you give a bit of context for this code base?

**Comment by warmist** [comment]
You are welcome to use it anyway you wish. I've licensed it under CC0 (i.e. public domain) as I feel it has almost no value. Based mostly of of [This](https://www.graphics.rwth-aachen.de/media/openmesh_static/Documentations/OpenMesh-6.3-Documentation/a00010.html) and [this very good document](https://fgiesen.wordpress.com/2012/02/21/half-edge-based-mesh-representations-theory/)

I've since moved changed my mind and think that this is probably the worst way to do mesh generation. It has very simple usage, but has huge overhead and implementation is hard to do correctly. Currently i think that better way of doing the same is [Winged edge data structure](https://en.wikipedia.org/wiki/Winged_edge) as it more closely mirrors e.g. how opengl stores meshes.

That said, i would be interested if you use it in anything. Good luck and have fun.

**Comment by jmiskovic** [comment]
Thanks for the info. I was drawn to the code exactly by simple usage demonstrated by tests. I'm currently using your code to generate some simple meshes, but I'll have to consider alternatives for more involved usage. Cheers.

![meshes](https://user-images.githubusercontent.com/17770782/80267676-fae38b00-86aa-11ea-8a66-d552f7054c49.gif)
